from enum import Enum
from typing import List
from pydantic import BaseModel, Field

class FactionType(str, Enum):
    HYPERSCALERS = "Hyperscalers"
    NEOCLOUDS = "NeoClouds"
    SOVEREIGN_REGIONAL = "Sovereign / Regional"
    DISTRIBUTED_EDGE = "Distributed / Edge"
    PRIVATE_ON_PREM = "Private / On-Prem"

class MythicProfile(BaseModel):
    epithet: str = Field(..., description="A theatrical, folk-style title (e.g., Lord of the Infinite Bill)")
    weapons: List[str] = Field(..., description="Legendary weapons forged from technical strengths")
    fatal_flaws: List[str] = Field(..., description="Curses/vulnerabilities forged from real weaknesses")
    battle_style: str = Field(..., description="The theatrical way this combatant fights")

class Champion(BaseModel):
    name: str = Field(..., description="The real-world name (e.g., AWS, Azure, CoreWeave)")
    faction: FactionType = Field(..., description="The faction category this champion belongs to")
    description: str = Field(..., description="Brief technical overview")
    mythic_profile: MythicProfile = Field(None, description="The mythic representation generated by Myth Weaver")
